### ISSUE TITLE
UNWRAP on `Err` value, resulting in program panic

### ISSUE THREAD

**Issue by SunHao-0** [Yoric/timer.rs#19]
Hi

Currently, I use `timer.rs` to set up delayed operations. Specifically, one global timer will be initialized at the beginning. Then, multiple threads will register the delayed operation and cancel the operation in certain conditions. The code is most like this:

``` rust

// Initialization 
static mut TIMER: Option<Timer> = None;
static ONCE: std::sync::Once = Once::new();

pub fn timer() -> &'static Timer{
    ONCE.call_once(|| unsafe {TIMER = Some(Timer::new())});

    unsafe{TIMER.as_ref().unwrap()}
}  

// Operation in each thead 
fn thead_foo(){
    let guard = timer().schedule_with_delay(Duration::seconds(20), || { do_something()});
    ....time_comsuming_work
  
   drop(guard);
}
```

However, this leads to `unwrap on Err value` and results in program panic after running for about 30 minutes.
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sync/mpsc/mod.rs:1130:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', .../timer-0.2.0/src/lib.rs:323:13
```

The setup code is [here](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/src/exec/util.rs#L79). Thread operation can be found [here](https://github.com/SunHao-0/healer/blob/main/syz_wrapper/src/exec/mod.rs#L385). The location that unwraps the Err value is [here](https://github.com/Yoric/timer.rs/blob/master/src/lib.rs#L329).

Waiting for your response and possible fix.

Thanks!

**Comment by SunHao-0** [comment]
I’ve replaced the implementation. This can be closed now.
